# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dc7362e5fd9ab880a59f12c32f09c8cf7815be99d381fc3f95022cef8e06d756e9f30ffaf5d1878bbe174132de0926f6411d129c061f5ea008883a325b60158

test:
  secret_key_base: 7642f70d81843c2a9d09fc3e0b13e9e8012d9d5be29081715395cc4928606f2ca17412bcf2278f8cad17c916d4ea156fa249aebf486443bd9f3e771ac3e417ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
